The error is fixed! Missing initialization of one integer caused it!

connectfour:

```console
########################Finish:
Maximum of 20000 reached
alreadyCounter: 439
```
